<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [

            // =====================================================
            // FREE WEIGHTS (category_id: 1)
            // =====================================================
            [
                'name'              => 'Cast Iron Dumbbell Set 5–25kg',
                'slug'              => 'cast-iron-dumbbell-set-5-25kg',
                'category_id'       => 1,
                'price'             => 18500.00,
                'compare_price'     => 22000.00,
                'sku'               => 'FW-DUMB-SET-25',
                'stock_quantity'    => 15,
                'brand'             => 'PowerFit',
                'short_description' => 'Complete 5–25kg cast iron dumbbell set with A-frame rack.',
                'description'       => 'Professional-grade cast iron dumbbells with hexagonal ends to prevent rolling. Includes A-frame storage rack. Perfect for home and commercial gyms.',
                'weight'            => 75.00,
                'is_featured'       => true,
                'is_new'            => false,
            ],
            [
                'name'              => 'Olympic Barbell 20kg',
                'slug'              => 'olympic-barbell-20kg',
                'category_id'       => 1,
                'price'             => 12000.00,
                'compare_price'     => null,
                'sku'               => 'FW-BAR-OLY-20',
                'stock_quantity'    => 8,
                'brand'             => 'IronEdge',
                'short_description' => 'Competition-grade 20kg Olympic barbell, 2.2m length.',
                'description'       => 'Knurled grip Olympic barbell with rotating sleeves. Rated for 300kg. 28mm grip diameter. Ideal for squats, deadlifts, and bench press.',
                'weight'            => 20.00,
                'is_featured'       => true,
                'is_new'            => true,
            ],
            [
                'name'              => 'Rubber Hex Dumbbell Pair 20kg',
                'slug'              => 'rubber-hex-dumbbell-pair-20kg',
                'category_id'       => 1,
                'price'             => 5500.00,
                'compare_price'     => 6500.00,
                'sku'               => 'FW-DUMB-HEX-20',
                'stock_quantity'    => 25,
                'brand'             => 'PowerFit',
                'short_description' => 'Rubber-coated hex dumbbells, sold as a pair.',
                'description'       => 'Premium rubber-coated hexagonal dumbbells with chrome handle. Non-slip grip, floor-safe coating. Perfect for home gym use. Sold as a pair.',
                'weight'            => 40.00,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'Adjustable Dumbbell 5–52.5kg',
                'slug'              => 'adjustable-dumbbell-5-52kg',
                'category_id'       => 1,
                'price'             => 42000.00,
                'compare_price'     => 50000.00,
                'sku'               => 'FW-DUMB-ADJ-52',
                'stock_quantity'    => 10,
                'brand'             => 'SelectFit',
                'short_description' => 'Dial-select adjustable dumbbell, replaces 15 pairs.',
                'description'       => 'Revolutionary dial-select technology lets you switch weights in seconds. Replaces 15 pairs of dumbbells. Compact tray included. Ideal for space-saving home gyms.',
                'weight'            => 24.00,
                'is_featured'       => true,
                'is_new'            => false,
            ],
            [
                'name'              => 'Weight Plates Set 100kg',
                'slug'              => 'weight-plates-set-100kg',
                'category_id'       => 1,
                'price'             => 28000.00,
                'compare_price'     => 33000.00,
                'sku'               => 'FW-PLATES-100',
                'stock_quantity'    => 6,
                'brand'             => 'IronEdge',
                'short_description' => '100kg rubber bumper plate set with Olympic holes.',
                'description'       => 'Full rubber bumper plate set in 1.25kg, 2.5kg, 5kg, 10kg, and 20kg denominations. Fits all standard 50mm Olympic bars. Dead bounce protection for home use.',
                'weight'            => 100.00,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'EZ Curl Bar with Collars',
                'slug'              => 'ez-curl-bar-with-collars',
                'category_id'       => 1,
                'price'             => 4800.00,
                'compare_price'     => null,
                'sku'               => 'FW-BAR-EZ-STD',
                'stock_quantity'    => 20,
                'brand'             => 'IronEdge',
                'short_description' => 'Standard EZ curl bar with spring collars included.',
                'description'       => 'Angled EZ curl bar reduces wrist strain during bicep and tricep exercises. Knurled grip zones. Includes spring collars. Compatible with standard 25mm plates.',
                'weight'            => 6.00,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Kettlebell 16kg',
                'slug'              => 'kettlebell-16kg',
                'category_id'       => 1,
                'price'             => 3800.00,
                'compare_price'     => 4500.00,
                'sku'               => 'FW-KB-16KG',
                'stock_quantity'    => 30,
                'brand'             => 'PowerFit',
                'short_description' => 'Cast iron competition kettlebell, 16kg.',
                'description'       => 'Single-piece cast iron kettlebell with flat base for stability. Smooth handle for comfortable swings. Colour-coded by weight. Suitable for swings, cleans, and Turkish get-ups.',
                'weight'            => 16.00,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'Pull-Up Bar Doorframe',
                'slug'              => 'pull-up-bar-doorframe',
                'category_id'       => 1,
                'price'             => 2900.00,
                'compare_price'     => 3500.00,
                'sku'               => 'FW-PULLUP-DOOR',
                'stock_quantity'    => 40,
                'brand'             => 'GripMaster',
                'short_description' => 'No-drill doorframe pull-up bar, fits 60–100cm frames.',
                'description'       => 'Heavy-duty steel pull-up bar with foam-padded handles. No screws needed. Supports up to 120kg. Multiple grip positions for wide, narrow, and neutral grips.',
                'weight'            => 2.50,
                'is_featured'       => false,
                'is_new'            => false,
            ],

            // =====================================================
            // CARDIO EQUIPMENT (category_id: 2)
            // =====================================================
            [
                'name'              => 'Commercial Treadmill T3',
                'slug'              => 'commercial-treadmill-t3',
                'category_id'       => 2,
                'price'             => 195000.00,
                'compare_price'     => 220000.00,
                'sku'               => 'CC-TREAD-T3',
                'stock_quantity'    => 3,
                'brand'             => 'CardioKing',
                'short_description' => '3.5HP motor, 0–20km/h, 15% incline, 7" touchscreen.',
                'description'       => 'Heavy-duty commercial treadmill built for daily intensive use. Features heart rate monitoring, 20 preset programs, MP3 connectivity, and cushioned running deck.',
                'weight'            => 120.00,
                'is_featured'       => true,
                'is_new'            => false,
            ],
            [
                'name'              => 'Spin Bike Pro 300',
                'slug'              => 'spin-bike-pro-300',
                'category_id'       => 2,
                'price'             => 55000.00,
                'compare_price'     => 65000.00,
                'sku'               => 'CC-SPIN-PRO300',
                'stock_quantity'    => 7,
                'brand'             => 'CardioKing',
                'short_description' => 'Belt-drive studio spin bike with 20kg flywheel.',
                'description'       => 'Whisper-quiet belt drive mechanism. 20kg flywheel for smooth pedalling. Adjustable handlebars and seat. LCD display showing speed, RPM, distance, and calories.',
                'weight'            => 45.00,
                'is_featured'       => true,
                'is_new'            => true,
            ],
            [
                'name'              => 'Rowing Machine Foldable',
                'slug'              => 'rowing-machine-foldable',
                'category_id'       => 2,
                'price'             => 38000.00,
                'compare_price'     => 45000.00,
                'sku'               => 'CC-ROW-FOLD',
                'stock_quantity'    => 5,
                'brand'             => 'AquaFit',
                'short_description' => 'Air-resistance rowing machine, folds for storage.',
                'description'       => 'Full-body air-resistance rowing machine with 8 resistance levels. Folds vertically for compact storage. Padded seat and ergonomic handle. Monitor tracks time, strokes, and calories.',
                'weight'            => 32.00,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Elliptical Cross Trainer E5',
                'slug'              => 'elliptical-cross-trainer-e5',
                'category_id'       => 2,
                'price'             => 72000.00,
                'compare_price'     => 85000.00,
                'sku'               => 'CC-ELLIP-E5',
                'stock_quantity'    => 4,
                'brand'             => 'CardioKing',
                'short_description' => 'Low-impact elliptical with 16 resistance levels.',
                'description'       => 'Smooth low-impact elliptical motion protects joints while delivering full-body cardio. 16 magnetic resistance levels. Heart rate grips. Backlit LCD display.',
                'weight'            => 85.00,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Jump Rope Speed Cable',
                'slug'              => 'jump-rope-speed-cable',
                'category_id'       => 2,
                'price'             => 1200.00,
                'compare_price'     => null,
                'sku'               => 'CC-JUMP-SPEED',
                'stock_quantity'    => 80,
                'brand'             => 'SpeedPro',
                'short_description' => 'Ball-bearing speed rope for double-unders.',
                'description'       => 'Professional speed jump rope with 360° ball-bearing handles. Adjustable steel cable. Comfortable foam grips. Ideal for HIIT, boxing, and CrossFit training.',
                'weight'            => 0.20,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'Assault Air Bike',
                'slug'              => 'assault-air-bike',
                'category_id'       => 2,
                'price'             => 89000.00,
                'compare_price'     => 100000.00,
                'sku'               => 'CC-AIRBIKE-AST',
                'stock_quantity'    => 4,
                'brand'             => 'AssaultFit',
                'short_description' => 'Unlimited resistance air bike for HIIT and conditioning.',
                'description'       => 'Fan-driven air resistance increases with effort — no limits. Dual-action arms and legs workout. Heavy-duty steel frame. Ideal for interval training and conditioning circuits.',
                'weight'            => 55.00,
                'is_featured'       => true,
                'is_new'            => false,
            ],

            // =====================================================
            // RESISTANCE BANDS (category_id: 3)
            // =====================================================
            [
                'name'              => 'Resistance Band Set (5 levels)',
                'slug'              => 'resistance-band-set-5-levels',
                'category_id'       => 3,
                'price'             => 3500.00,
                'compare_price'     => 4500.00,
                'sku'               => 'RB-SET-5LVL',
                'stock_quantity'    => 50,
                'brand'             => 'FlexPro',
                'short_description' => 'Set of 5 latex resistance bands, 5–40kg resistance.',
                'description'       => 'Premium latex resistance bands in 5 resistance levels (5kg, 10kg, 20kg, 30kg, 40kg). Includes carry bag and exercise guide. Perfect for warm-up, rehab, and strength training.',
                'weight'            => 0.50,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'Fabric Booty Bands 3-Pack',
                'slug'              => 'fabric-booty-bands-3-pack',
                'category_id'       => 3,
                'price'             => 1800.00,
                'compare_price'     => 2200.00,
                'sku'               => 'RB-BOOTY-FAB3',
                'stock_quantity'    => 60,
                'brand'             => 'FlexPro',
                'short_description' => 'Non-slip fabric resistance bands for glutes and legs.',
                'description'       => 'Thick fabric construction prevents rolling and slipping. Three resistance levels: light, medium, heavy. Ideal for glute activation, squats, and hip thrusts.',
                'weight'            => 0.30,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Power Band Heavy 50–120lb',
                'slug'              => 'power-band-heavy-50-120lb',
                'category_id'       => 3,
                'price'             => 2400.00,
                'compare_price'     => null,
                'sku'               => 'RB-POWER-HVY',
                'stock_quantity'    => 35,
                'brand'             => 'ElasticForce',
                'short_description' => 'Heavy resistance loop band for pull-ups and deadlifts.',
                'description'       => 'Extra-thick natural latex power band. Use for assisted pull-ups, powerlifting, stretching, and mobility. 50–120lb resistance. 100% natural latex.',
                'weight'            => 0.60,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Tube Resistance Bands with Handles',
                'slug'              => 'tube-resistance-bands-with-handles',
                'category_id'       => 3,
                'price'             => 2800.00,
                'compare_price'     => 3200.00,
                'sku'               => 'RB-TUBE-HANDLE',
                'stock_quantity'    => 45,
                'brand'             => 'FlexPro',
                'short_description' => 'Set of 5 tube bands with foam handles and door anchor.',
                'description'       => 'Versatile tube resistance bands with comfortable foam handles. Includes door anchor, ankle straps, and carry bag. 5 resistance levels from 5lb to 50lb.',
                'weight'            => 0.80,
                'is_featured'       => false,
                'is_new'            => true,
            ],

            // =====================================================
            // GYM APPAREL (category_id: 4)
            // =====================================================
            [
                'name'              => 'Dry-Fit Training Tee',
                'slug'              => 'dry-fit-training-tee',
                'category_id'       => 4,
                'price'             => 2200.00,
                'compare_price'     => null,
                'sku'               => 'APP-TEE-DRY-M',
                'stock_quantity'    => 100,
                'brand'             => 'GymFit',
                'short_description' => 'Moisture-wicking performance tee for intense workouts.',
                'description'       => 'Ultra-lightweight dry-fit training tee with 4-way stretch fabric. Anti-odour technology. Available in S, M, L, XL, XXL. Machine washable.',
                'weight'            => 0.20,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Compression Shorts 7"',
                'slug'              => 'compression-shorts-7-inch',
                'category_id'       => 4,
                'price'             => 3200.00,
                'compare_price'     => 3800.00,
                'sku'               => 'APP-SHORT-COMP7',
                'stock_quantity'    => 75,
                'brand'             => 'GymFit',
                'short_description' => 'High-compression shorts with muscle support technology.',
                'description'       => 'Graduated compression supports key muscle groups and improves blood flow. Quick-dry fabric. Flatlock stitching prevents chafing. Built-in brief liner.',
                'weight'            => 0.25,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'Weightlifting Belt Leather 10cm',
                'slug'              => 'weightlifting-belt-leather-10cm',
                'category_id'       => 4,
                'price'             => 6500.00,
                'compare_price'     => 8000.00,
                'sku'               => 'APP-BELT-LEATH',
                'stock_quantity'    => 20,
                'brand'             => 'IronEdge',
                'short_description' => 'Genuine leather 10cm wide powerlifting belt.',
                'description'       => 'Premium full-grain leather weightlifting belt with double-prong buckle. 10cm uniform width for maximum back support. Breaks in with use. Available in S, M, L, XL.',
                'weight'            => 1.20,
                'is_featured'       => true,
                'is_new'            => false,
            ],
            [
                'name'              => 'Gym Gloves with Wrist Wrap',
                'slug'              => 'gym-gloves-with-wrist-wrap',
                'category_id'       => 4,
                'price'             => 2800.00,
                'compare_price'     => 3200.00,
                'sku'               => 'APP-GLOVE-WRAP',
                'stock_quantity'    => 55,
                'brand'             => 'GripMaster',
                'short_description' => 'Half-finger workout gloves with integrated wrist support.',
                'description'       => 'Padded palm protection with textured grip. Integrated wrist wrap provides support during heavy lifts. Easy-off tab. Machine washable. Available in S/M and L/XL.',
                'weight'            => 0.30,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Hoodie Fleece Zip-Up',
                'slug'              => 'hoodie-fleece-zip-up',
                'category_id'       => 4,
                'price'             => 4500.00,
                'compare_price'     => 5500.00,
                'sku'               => 'APP-HOOD-FLEECE',
                'stock_quantity'    => 60,
                'brand'             => 'GymFit',
                'short_description' => 'Heavyweight fleece zip-up hoodie for post-workout warmth.',
                'description'       => 'Thick fleece lining keeps you warm during warm-up and cool-down. Full zip with kangaroo pocket. Ribbed cuffs and hem. Available in 5 colours.',
                'weight'            => 0.70,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'Knee Sleeves 7mm Pair',
                'slug'              => 'knee-sleeves-7mm-pair',
                'category_id'       => 4,
                'price'             => 3800.00,
                'compare_price'     => null,
                'sku'               => 'APP-KNEE-7MM',
                'stock_quantity'    => 40,
                'brand'             => 'IronEdge',
                'short_description' => '7mm neoprene knee sleeves for squats and leg press.',
                'description'       => 'Competition-grade 7mm neoprene provides warmth and compression for knee joint support. Ideal for squats, leg press, and Olympic lifting. Sold as a pair. Sizes S–XXL.',
                'weight'            => 0.40,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Yoga Leggings High Waist',
                'slug'              => 'yoga-leggings-high-waist',
                'category_id'       => 4,
                'price'             => 3600.00,
                'compare_price'     => 4200.00,
                'sku'               => 'APP-LEG-YOGA-HW',
                'stock_quantity'    => 80,
                'brand'             => 'GymFit',
                'short_description' => 'High-waist compression leggings with squat-proof fabric.',
                'description'       => 'Four-way stretch squat-proof fabric. High waistband with tummy control. Moisture-wicking and breathable. Side pocket for phone. Available in 6 colours.',
                'weight'            => 0.30,
                'is_featured'       => false,
                'is_new'            => true,
            ],

            // =====================================================
            // SUPPLEMENTS (category_id: 5)
            // =====================================================
            [
                'name'              => 'Whey Protein Isolate 2kg',
                'slug'              => 'whey-protein-isolate-2kg',
                'category_id'       => 5,
                'price'             => 14500.00,
                'compare_price'     => 16000.00,
                'sku'               => 'SUPP-WHEY-2KG',
                'stock_quantity'    => 30,
                'brand'             => 'NutriFit',
                'short_description' => '27g protein per serving, 67 servings per tub.',
                'description'       => 'Premium cold-processed whey protein isolate. 90% protein by weight. Fast absorbing. Available in Chocolate, Vanilla, and Strawberry. Lab tested, certified clean.',
                'weight'            => 2.00,
                'is_featured'       => true,
                'is_new'            => false,
            ],
            [
                'name'              => 'Creatine Monohydrate 500g',
                'slug'              => 'creatine-monohydrate-500g',
                'category_id'       => 5,
                'price'             => 4200.00,
                'compare_price'     => 5000.00,
                'sku'               => 'SUPP-CREAT-500',
                'stock_quantity'    => 45,
                'brand'             => 'NutriFit',
                'short_description' => 'Pure micronised creatine monohydrate, 100 servings.',
                'description'       => 'Pharmaceutical-grade micronised creatine for rapid absorption. Unflavoured — mixes into any drink. Clinically proven to increase strength and power output. 5g per serving.',
                'weight'            => 0.55,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Pre-Workout Energy Boost 300g',
                'slug'              => 'pre-workout-energy-boost-300g',
                'category_id'       => 5,
                'price'             => 5800.00,
                'compare_price'     => 7000.00,
                'sku'               => 'SUPP-PRE-300',
                'stock_quantity'    => 25,
                'brand'             => 'ExplosiveFuel',
                'short_description' => 'High-stim pre-workout with caffeine, beta-alanine, and citrulline.',
                'description'       => 'Explosive energy formula with 200mg caffeine, 3.2g beta-alanine, 6g L-citrulline, and B vitamins. Fruit Punch and Blue Raspberry flavours. 30 servings.',
                'weight'            => 0.35,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'BCAA 2:1:1 Powder 400g',
                'slug'              => 'bcaa-2-1-1-powder-400g',
                'category_id'       => 5,
                'price'             => 3800.00,
                'compare_price'     => null,
                'sku'               => 'SUPP-BCAA-400',
                'stock_quantity'    => 40,
                'brand'             => 'NutriFit',
                'short_description' => 'Branched-chain amino acids in optimal 2:1:1 ratio.',
                'description'       => 'Essential BCAAs (Leucine, Isoleucine, Valine) in the scientifically optimal 2:1:1 ratio. Supports muscle recovery, reduces soreness, and prevents muscle breakdown during training.',
                'weight'            => 0.45,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Mass Gainer 5kg',
                'slug'              => 'mass-gainer-5kg',
                'category_id'       => 5,
                'price'             => 18000.00,
                'compare_price'     => 21000.00,
                'sku'               => 'SUPP-MASS-5KG',
                'stock_quantity'    => 15,
                'brand'             => 'BulkUp',
                'short_description' => '1250 calories per serving, 50g protein, ideal for hardgainers.',
                'description'       => 'High-calorie mass gainer with complex carbohydrates and premium protein blend. 1250 calories, 50g protein, 252g carbs per serving. Chocolate and Vanilla flavours.',
                'weight'            => 5.50,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Multivitamin Sport 90 Tabs',
                'slug'              => 'multivitamin-sport-90-tabs',
                'category_id'       => 5,
                'price'             => 2500.00,
                'compare_price'     => 3000.00,
                'sku'               => 'SUPP-MULTI-90',
                'stock_quantity'    => 55,
                'brand'             => 'NutriFit',
                'short_description' => 'Complete sport multivitamin with 25 vitamins and minerals.',
                'description'       => 'Comprehensive multivitamin formula designed for athletes. 25 essential vitamins and minerals including Vitamin D3, Zinc, Magnesium, and B-complex. 3 tablets per day, 30-day supply.',
                'weight'            => 0.15,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'Omega-3 Fish Oil 1000mg 90 Caps',
                'slug'              => 'omega-3-fish-oil-1000mg-90-caps',
                'category_id'       => 5,
                'price'             => 1800.00,
                'compare_price'     => null,
                'sku'               => 'SUPP-OMEGA3-90',
                'stock_quantity'    => 70,
                'brand'             => 'NutriFit',
                'short_description' => 'High-potency Omega-3 for joint health and recovery.',
                'description'       => 'Pharmaceutical-grade fish oil with 300mg EPA and 200mg DHA per capsule. Supports joint health, reduces inflammation, and improves cardiovascular health. Enteric coated — no fishy aftertaste.',
                'weight'            => 0.20,
                'is_featured'       => false,
                'is_new'            => false,
            ],

            // =====================================================
            // ACCESSORIES (category_id: 6)
            // =====================================================
            [
                'name'              => 'Foam Roller High Density 90cm',
                'slug'              => 'foam-roller-high-density-90cm',
                'category_id'       => 6,
                'price'             => 2800.00,
                'compare_price'     => 3500.00,
                'sku'               => 'ACC-FOAM-90CM',
                'stock_quantity'    => 35,
                'brand'             => 'RecoverPro',
                'short_description' => 'Extra-firm 90cm foam roller for deep tissue massage.',
                'description'       => 'High-density EVA foam roller for myofascial release and muscle recovery. 90cm length targets full back, ITB, quads, and calves. Grid texture for targeted pressure points.',
                'weight'            => 0.80,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Gym Bag Duffel 40L',
                'slug'              => 'gym-bag-duffel-40l',
                'category_id'       => 6,
                'price'             => 4200.00,
                'compare_price'     => 5000.00,
                'sku'               => 'ACC-BAG-DUF-40',
                'stock_quantity'    => 28,
                'brand'             => 'GymFit',
                'short_description' => 'Spacious 40L duffel with shoe compartment and wet pocket.',
                'description'       => 'Water-resistant 600D polyester construction. Separate shoe compartment, wet/dry pocket, padded laptop sleeve. Detachable shoulder strap. Available in 4 colours.',
                'weight'            => 0.90,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'Shaker Bottle 700ml',
                'slug'              => 'shaker-bottle-700ml',
                'category_id'       => 6,
                'price'             => 950.00,
                'compare_price'     => null,
                'sku'               => 'ACC-SHAKE-700',
                'stock_quantity'    => 120,
                'brand'             => 'NutriFit',
                'short_description' => 'Leak-proof 700ml shaker with BlenderBall wire whisk.',
                'description'       => 'BPA-free Tritan plastic shaker with secure flip lid. Includes BlenderBall wire whisk for lump-free protein shakes. Graduated markings in ml and oz. Dishwasher safe.',
                'weight'            => 0.20,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Yoga Mat Non-Slip 6mm',
                'slug'              => 'yoga-mat-non-slip-6mm',
                'category_id'       => 6,
                'price'             => 3200.00,
                'compare_price'     => 4000.00,
                'sku'               => 'ACC-MAT-YOGA-6',
                'stock_quantity'    => 50,
                'brand'             => 'FlexPro',
                'short_description' => 'Premium non-slip TPE yoga mat with alignment lines.',
                'description'       => 'Eco-friendly TPE construction — no PVC or latex. Double-sided non-slip texture. Alignment lines for correct positioning. Includes carry strap. 183cm x 61cm x 6mm.',
                'weight'            => 1.20,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Gymnastic Rings Wooden 28mm',
                'slug'              => 'gymnastic-rings-wooden-28mm',
                'category_id'       => 6,
                'price'             => 4500.00,
                'compare_price'     => 5200.00,
                'sku'               => 'ACC-RINGS-WOOD',
                'stock_quantity'    => 22,
                'brand'             => 'GripMaster',
                'short_description' => 'Birch wood gymnastic rings with 4.5m numbered straps.',
                'description'       => 'Competition-spec birch wood rings, 28mm diameter. Smooth finish for comfort. Includes 4.5m buckle straps with numbered markings for quick height adjustment. Rated to 400kg.',
                'weight'            => 1.10,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'Battle Rope 15m x 38mm',
                'slug'              => 'battle-rope-15m-38mm',
                'category_id'       => 6,
                'price'             => 8500.00,
                'compare_price'     => 10000.00,
                'sku'               => 'ACC-ROPE-BAT15',
                'stock_quantity'    => 12,
                'brand'             => 'PowerFit',
                'short_description' => '15m poly dacron battle rope with anchor strap.',
                'description'       => 'Heavy poly dacron battle rope for conditioning and HIIT. 38mm diameter, 15m length. Includes anchor strap and end caps. Builds upper body, core, and cardiovascular endurance.',
                'weight'            => 15.00,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Ab Roller Wheel with Knee Pad',
                'slug'              => 'ab-roller-wheel-with-knee-pad',
                'category_id'       => 6,
                'price'             => 1500.00,
                'compare_price'     => 1900.00,
                'sku'               => 'ACC-ABROLL',
                'stock_quantity'    => 65,
                'brand'             => 'CoreFit',
                'short_description' => 'Double-wheel ab roller with thick foam knee pad.',
                'description'       => 'Wide double-wheel design for stability. Non-slip rubber wheel tread. Ergonomic foam handles. Includes thick foam knee pad. Works abs, obliques, back, and shoulders.',
                'weight'            => 0.60,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Pull-Up Assist Band Set',
                'slug'              => 'pull-up-assist-band-set',
                'category_id'       => 6,
                'price'             => 3200.00,
                'compare_price'     => null,
                'sku'               => 'ACC-PULLUP-ASST',
                'stock_quantity'    => 30,
                'brand'             => 'ElasticForce',
                'short_description' => 'Set of 3 pull-up assist bands for beginners to advanced.',
                'description'       => 'Three resistance levels assist with pull-ups as you build strength. Also used for mobility, stretching, and powerlifting warm-ups. 100% natural latex. Sold as a set of 3.',
                'weight'            => 0.70,
                'is_featured'       => false,
                'is_new'            => true,
            ],
            [
                'name'              => 'Dip Belt Heavy Duty',
                'slug'              => 'dip-belt-heavy-duty',
                'category_id'       => 6,
                'price'             => 2600.00,
                'compare_price'     => 3000.00,
                'sku'               => 'ACC-DIP-BELT',
                'stock_quantity'    => 18,
                'brand'             => 'IronEdge',
                'short_description' => 'Steel chain dip belt for weighted pull-ups and dips.',
                'description'       => 'Heavy-duty nylon belt with 90cm steel chain. Rated to 200kg. Wide padded waistband prevents hip digging. Use for weighted dips, pull-ups, and belt squats.',
                'weight'            => 0.90,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Speed Agility Ladder 6m',
                'slug'              => 'speed-agility-ladder-6m',
                'category_id'       => 6,
                'price'             => 1800.00,
                'compare_price'     => 2200.00,
                'sku'               => 'ACC-AGILITY-6M',
                'stock_quantity'    => 40,
                'brand'             => 'SpeedPro',
                'short_description' => '6m agility ladder with adjustable rungs and carry bag.',
                'description'       => 'Flat nylon agility ladder with 12 adjustable plastic rungs. 6 metres total length. Ideal for speed, footwork, and coordination drills. Includes carry bag and training guide.',
                'weight'            => 0.40,
                'is_featured'       => false,
                'is_new'            => false,
            ],
            [
                'name'              => 'Suspension Trainer TRX-Style',
                'slug'              => 'suspension-trainer-trx-style',
                'category_id'       => 6,
                'price'             => 7500.00,
                'compare_price'     => 9000.00,
                'sku'               => 'ACC-SUSPEND-TRX',
                'stock_quantity'    => 16,
                'brand'             => 'SuspendFit',
                'short_description' => 'Full-body suspension trainer with door and ceiling anchors.',
                'description'       => 'Commercial-grade nylon straps with padded handles and foot cradles. Adjustable length. Includes door anchor, ceiling mount, and carry bag. 200+ exercises possible.',
                'weight'            => 0.85,
                'is_featured'       => true,
                'is_new'            => false,
            ],
            [
                'name'              => 'Chalk Block Gym Chalk 8-Pack',
                'slug'              => 'chalk-block-gym-chalk-8-pack',
                'category_id'       => 6,
                'price'             => 1200.00,
                'compare_price'     => null,
                'sku'               => 'ACC-CHALK-8PK',
                'stock_quantity'    => 90,
                'brand'             => 'GripMaster',
                'short_description' => 'Pure magnesium carbonate gym chalk, pack of 8 blocks.',
                'description'       => 'Professional-grade magnesium carbonate chalk for maximum grip. Reduces moisture and improves bar contact. Used by powerlifters, gymnasts, and climbers. 8 x 56g blocks per box.',
                'weight'            => 0.50,
                'is_featured'       => false,
                'is_new'            => false,
            ],
        ];

        foreach ($products as $product) {
            // Skip if slug already exists
            if (DB::table('products')->where('slug', $product['slug'])->exists()) {
                continue;
            }

            DB::table('products')->insert(array_merge($product, [
                'in_stock'       => true,
                'track_quantity' => true,
                'is_active'      => true,
                'average_rating' => 0,
                'reviews_count'  => 0,
                'sales_count'    => 0,
                'created_at'     => now(),
                'updated_at'     => now(),
            ]));
        }

        $this->command->info('✓ 50 products seeded across 6 categories.');
    }
}